[package]
name = "tree-sitter-css"
description = "CSS grammar for tree-sitter"
version = "0.19.0"
keywords = ["incremental", "parsing", "css"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/tree-sitter/tree-sitter-css"
edition = "2021"
license = "MIT"
authors = ["Max Brunsfeld <maxbrunsfeld@gmail.com>"]
autoexamples = false

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = ">= 0.19"

[build-dependencies]
cc = "1.0"
