[package]
name = "tree-sitter-smali"
version = "0.0.1"
authors = ["Yotam Nachum", "Amaan Qureshi <amaanq12@gmail.com>"]
description = "smali grammar for the tree-sitter parsing library"
keywords = ["incremental", "parsing", "smali"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/amaanq/tree-sitter-smali"
edition = "2021"
license = "MIT"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.20"

[build-dependencies]
cc = "1.0"
