[package]
name = "tree-sitter-smali"
description = "Smali grammar for tree-sitter"
version = "0.0.2"
authors = ["Yotam Nachum <me@yotam.net>", "Amaan Qureshi <amaanq12@gmail.com>"]
keywords = ["incremental", "parsing", "smali"]
categories = ["parsing", "text-editors"]
repository = "https://git.sr.ht/~yotam/tree-sitter-smali"
edition = "2021"
license = "MIT"

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.20.3"

[build-dependencies]
cc = "1.0"
