name: Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Generate parser
        run: npm run generate
      - name: Verify that generated parser matches repo
        run: |
          git diff HEAD
          test -z "$(git diff HEAD)"
      - name: Run tests
        run: npm test
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build and test crate
        uses: actions-rs/cargo@v1
        with:
          command: test
