name: Test full Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Npm install tree-sitter
        run: |
          npm i tree-sitter
      - name: Npm install
        run: |
          npm run build
      - name: Npm install
        run: |
          npm i
      - name: Unit tests
        run: |
          npm test
